apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: maintenance-api-event-enhancer
spec:
  environments:
    - name: development
      build:
        from: main
  components:
    - name: api
      dockerfileName: Equinor.Maintenance.API.EventEnhancer/Dockerfile
      publicPort: http
      ports:
        - name: http
          port: 5005
      secrets:
        - AzureAd__ClientSecret
      ingressConfiguration:
        - leastconnectedlb
      environmentConfig:
        - environment: development
          variables:
            ASPNETCORE_ENVIRONMENT: "Development"
    
