apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: maintenance-api-event-enhancer
spec:
  environments:
    - name: sandbox
      build:
        from: main
    - name: test
    - name: qa
#    - name: production
  components:
    - name: api
      src: Equinor.Maintenance.API.EventEnhancer
      publicPort: http
      ports:
        - name: http
          port: 5005
      secrets:
        - AzureAd__ClientSecret
      ingressConfiguration:
        - leastconnectedlb
      environmentConfig:
        - environment: sandbox
          variables:
            ASPNETCORE_ENVIRONMENT: "Sandbox"
        - environment: test
          variables:
            ASPNETCORE_ENVIRONMENT: "Test"
        - environment: qa
          variables:
            ASPNETCORE_ENVIRONMENT: "QA"
#        - environment: production
#          variables:
#            ASPNETCORE_ENVIRONMENT: "Production"
